//! Parameter fields that strip whitespace, recorded from the models.
//!
//! Produced by `scripts/gen_registry.py`. A field is here exactly when
//! its annotation in `src/vogt/application/models.py` is `Name` or
//! `Reason`, the two types that strip. A field of the same name typed
//! `str` is absent, and must stay absent: stripping it would change
//! stored text, and with it the audit digest.

/// `(operation, field)`, in registry order.
pub static STRIPS: &[(&str, &str)] = &[
    ("project.register", "name"),
    ("project.register", "reason"),
    ("project.create", "name"),
    ("project.create", "reason"),
    ("project.import", "reason"),
    ("project.update", "reason"),
    ("project.transition", "reason"),
    ("work.create", "title"),
    ("work.create", "reason"),
    ("work.update", "title"),
    ("work.update", "reason"),
    ("work.transition", "reason"),
    ("work.relate", "reason"),
    ("work.unrelate", "reason"),
    ("work.bind_branch", "reason"),
    ("work.comment", "body"),
    ("work.comment", "reason"),
    ("label.create", "name"),
    ("label.create", "reason"),
    ("initiative.create", "title"),
    ("initiative.create", "reason"),
    ("initiative.update", "title"),
    ("initiative.update", "reason"),
    ("initiative.publish", "reason"),
    ("actor.create", "identity_ref"),
    ("actor.create", "display_name"),
    ("actor.create", "reason"),
    ("sweep", "reason"),
    ("observations.prune", "reason"),
    ("suppress", "reason"),
    ("suppression.revoke", "reason"),
    ("work.adopt", "reason"),
    ("contract.check", "reason"),
    ("contract.adopt", "reason"),
    ("contract.decline", "reason"),
    ("contract.inapplicable", "reason"),
    ("contract.applicable", "reason"),
    ("project.scaffold", "reason"),
    ("drift.detect", "reason"),
    ("drift.resolve", "reason"),
    ("session.start", "reason"),
    ("session.stop", "reason"),
    ("session.input", "reason"),
    ("session.hibernate", "reason"),
    ("session.wake", "reason"),
    ("session.keep_awake", "reason"),
    ("session.rename", "reason"),
    ("session.remove", "reason"),
    ("session.set_role", "reason"),
    ("session.bind_work", "reason"),
    ("session.grant_request", "reason"),
    ("session.grant_decide", "reason"),
    ("session.grant_revoke", "reason"),
    ("session.answer", "reason"),
    ("session.token", "reason"),
    ("session.report_blocked", "reason"),
    ("session.report_unblocked", "reason"),
    ("agent_cli.update", "reason"),
    ("token.issue", "actor"),
    ("token.issue", "name"),
    ("token.issue", "scopes"),
    ("token.issue", "reason"),
    ("token.revoke", "reason"),
    ("auth.logout", "reason"),
    ("user.create", "username"),
    ("user.create", "display_name"),
    ("user.create", "actor"),
    ("user.create", "scopes"),
    ("user.create", "reason"),
    ("user.set_password", "username"),
    ("user.set_password", "scopes"),
    ("user.set_password", "reason"),
    ("user.remove", "username"),
    ("user.remove", "reason"),
    ("backup", "reason"),
    ("restore", "reason"),
    ("clone", "reason"),
    ("export", "reason"),
    ("import", "reason"),
    ("forge.onboard", "reason"),
    ("forge.writeback", "reason"),
    ("forge.link", "reason"),
    ("forge.publish", "reason"),
    ("forge.account_link", "reason"),
    ("forge.account_unlink", "reason"),
    ("forge.import", "reason"),
    ("inbox.archive", "reason"),
    ("inbox.snooze", "reason"),
    ("inbox.restore", "reason"),
    ("preference.set", "reason"),
    ("chat.create", "reason"),
    ("chat.send", "reason"),
    ("chat.decide", "reason"),
    ("chat.set_model", "reason"),
    ("chat.interrupt", "reason"),
    ("chat.archive", "reason"),
    ("chat.promote", "reason"),
];
