"""The M1 operation set.

Every capability of the product, defined once. Adding an entry here is what
gives an operation a CLI command, a REST route with request and response
schemas, and an MCP tool — and the parity harness fails if any of the three
is missing (FR-A1, FR-A3).
"""

from __future__ import annotations

from typing import Any

from vogt.application import services
from vogt.application.models import (
    ActorListResult,
    ActorResult,
    AdoptParams,
    AdoptResult,
    AuditListResult,
    BacklogParams,
    BacklogResult,
    BugsParams,
    CommentParams,
    CommentResult,
    CoverageParams,
    CoverageResult,
    CreateActorParams,
    CreateInitiativeParams,
    CreateLabelParams,
    CreateProjectParams,
    CreateProjectResult,
    CreateWorkParams,
    DepsParams,
    DepsResult,
    EventListResult,
    GetProjectParams,
    GetWorkParams,
    InitiativeListResult,
    InitiativeResult,
    InitParams,
    InitResult,
    LabelListResult,
    LabelResult,
    ListActorsParams,
    ListAuditParams,
    ListEventsParams,
    ListInitiativesParams,
    ListLabelsParams,
    ListProjectsParams,
    ListSuppressionsParams,
    ListWorkParams,
    McpStdioParams,
    McpStdioResult,
    ObservationsParams,
    ObservationsResult,
    ProjectBriefParams,
    ProjectBriefResult,
    ProjectListResult,
    ProjectResult,
    PruneParams,
    PruneResult,
    RegisterProjectParams,
    RelateWorkParams,
    RevokeSuppressionParams,
    StatusParams,
    StatusResult,
    SuppressionListResult,
    SuppressionResult,
    SuppressParams,
    SweepParams,
    SweepResult,
    TransitionProjectParams,
    TransitionWorkParams,
    UnrelateWorkParams,
    UpdateWorkParams,
    WhyParams,
    WhyResult,
    WorkflowListParams,
    WorkflowListResult,
    WorkListResult,
    WorkResult,
)
from vogt.registry.operation import CliBinding, HttpRoute, Operation


def build_operations() -> list[Operation[Any, Any]]:
    """Define every operation the M1 build exposes."""
    return [
        # -- instance ------------------------------------------------------
        Operation(
            name="init",
            summary="Create or bring forward the instance in the data directory.",
            scope="admin",
            mutating=False,
            params_model=InitParams,
            result_model=InitResult,
            handler=services.init_instance,
            route=HttpRoute("POST", "/instance/init"),
            cli=CliBinding(("init",)),
        ),
        Operation(
            name="status",
            summary="Report instance identity, schema versions, and row counts.",
            scope="read",
            mutating=False,
            params_model=StatusParams,
            result_model=StatusResult,
            handler=services.status,
            route=HttpRoute("GET", "/status"),
            cli=CliBinding(("status",)),
        ),
        Operation(
            name="mcp.stdio",
            summary="Serve MCP over stdin/stdout until the stream closes.",
            scope="read",
            mutating=False,
            params_model=McpStdioParams,
            result_model=McpStdioResult,
            handler=services.serve_mcp_stdio,
            route=HttpRoute("POST", "/mcp/stdio"),
            cli=CliBinding(("mcp", "stdio")),
        ),
        # -- projects ------------------------------------------------------
        Operation(
            name="project.register",
            summary="Register an existing folder or repository as a project.",
            scope="project.write",
            mutating=True,
            params_model=RegisterProjectParams,
            result_model=ProjectResult,
            handler=services.register_project,
            route=HttpRoute("POST", "/projects"),
            cli=CliBinding(("project", "register")),
        ),
        Operation(
            name="project.create",
            summary="Scaffold a contract-compliant skeleton, then register it.",
            scope="project.write",
            mutating=True,
            params_model=CreateProjectParams,
            result_model=CreateProjectResult,
            handler=services.create_project,
            route=HttpRoute("POST", "/projects/create"),
            cli=CliBinding(("project", "create")),
        ),
        Operation(
            name="project.get",
            summary="Fetch one project by slug.",
            scope="read",
            mutating=False,
            params_model=GetProjectParams,
            result_model=ProjectResult,
            handler=services.get_project,
            route=HttpRoute("GET", "/projects/get"),
            cli=CliBinding(("project", "get")),
        ),
        Operation(
            name="project.list",
            summary="List registered projects.",
            scope="read",
            mutating=False,
            params_model=ListProjectsParams,
            result_model=ProjectListResult,
            handler=services.list_projects,
            route=HttpRoute("GET", "/projects"),
            cli=CliBinding(("project", "list")),
        ),
        Operation(
            name="project.brief",
            summary="The per-repo view: state, work, bugs, version, compliance.",
            scope="read",
            mutating=False,
            params_model=ProjectBriefParams,
            result_model=ProjectBriefResult,
            handler=services.brief_project,
            route=HttpRoute("GET", "/projects/brief"),
            cli=CliBinding(("project", "brief")),
        ),
        Operation(
            name="project.transition",
            summary="Move a project through its lifecycle states.",
            scope="project.write",
            mutating=True,
            params_model=TransitionProjectParams,
            result_model=ProjectResult,
            handler=services.transition_project,
            route=HttpRoute("POST", "/projects/transition"),
            cli=CliBinding(("project", "transition")),
        ),
        # -- work ----------------------------------------------------------
        Operation(
            name="work.create",
            summary="Create a work item (feature / bug / chore / question).",
            scope="work.write",
            mutating=True,
            params_model=CreateWorkParams,
            result_model=WorkResult,
            handler=services.create_work,
            route=HttpRoute("POST", "/work"),
            cli=CliBinding(("work", "create")),
        ),
        Operation(
            name="work.get",
            summary="Fetch one work item with its relations, labels and comments.",
            scope="read",
            mutating=False,
            params_model=GetWorkParams,
            result_model=WorkResult,
            handler=services.get_work,
            route=HttpRoute("GET", "/work/get"),
            cli=CliBinding(("work", "get")),
        ),
        Operation(
            name="work.list",
            summary="List work items with filters.",
            scope="read",
            mutating=False,
            params_model=ListWorkParams,
            result_model=WorkListResult,
            handler=services.list_work,
            route=HttpRoute("GET", "/work"),
            cli=CliBinding(("work", "list")),
        ),
        Operation(
            name="work.update",
            summary="Change a work item's fields, assignee, or labels.",
            scope="work.write",
            mutating=True,
            params_model=UpdateWorkParams,
            result_model=WorkResult,
            handler=services.update_work,
            route=HttpRoute("POST", "/work/update"),
            cli=CliBinding(("work", "update")),
        ),
        Operation(
            name="work.transition",
            summary="Move a work item to another state, validating the edge.",
            scope="work.write",
            mutating=True,
            params_model=TransitionWorkParams,
            result_model=WorkResult,
            handler=services.transition_work,
            route=HttpRoute("POST", "/work/transition"),
            cli=CliBinding(("work", "transition")),
        ),
        Operation(
            name="work.relate",
            summary="Add a typed relation between two work items.",
            scope="work.write",
            mutating=True,
            params_model=RelateWorkParams,
            result_model=WorkResult,
            handler=services.relate_work,
            route=HttpRoute("POST", "/work/relate"),
            cli=CliBinding(("work", "relate")),
        ),
        Operation(
            name="work.unrelate",
            summary="Remove a typed relation between two work items.",
            scope="work.write",
            mutating=True,
            params_model=UnrelateWorkParams,
            result_model=WorkResult,
            handler=services.unrelate_work,
            route=HttpRoute("POST", "/work/unrelate"),
            cli=CliBinding(("work", "unrelate")),
        ),
        Operation(
            name="work.comment",
            summary="Comment on a work item, attributed to the acting actor.",
            scope="work.write",
            mutating=True,
            params_model=CommentParams,
            result_model=CommentResult,
            handler=services.comment_work,
            route=HttpRoute("POST", "/work/comment"),
            cli=CliBinding(("work", "comment")),
        ),
        # -- views ---------------------------------------------------------
        Operation(
            name="backlog",
            summary="The ranked backlog, globally or for one project.",
            scope="read",
            mutating=False,
            params_model=BacklogParams,
            result_model=BacklogResult,
            handler=services.backlog,
            route=HttpRoute("GET", "/backlog"),
            cli=CliBinding(("backlog",)),
        ),
        Operation(
            name="bugs",
            summary="Open bugs across every project, ranked.",
            scope="read",
            mutating=False,
            params_model=BugsParams,
            result_model=BacklogResult,
            handler=services.bugs,
            route=HttpRoute("GET", "/bugs"),
            cli=CliBinding(("bugs",)),
        ),
        Operation(
            name="why",
            summary="Per-input score contributions for one ranked item.",
            scope="read",
            mutating=False,
            params_model=WhyParams,
            result_model=WhyResult,
            handler=services.why,
            route=HttpRoute("GET", "/why"),
            cli=CliBinding(("why",)),
        ),
        # -- taxonomy ------------------------------------------------------
        Operation(
            name="label.create",
            summary="Define a label.",
            scope="work.write",
            mutating=True,
            params_model=CreateLabelParams,
            result_model=LabelResult,
            handler=services.create_label,
            route=HttpRoute("POST", "/labels"),
            cli=CliBinding(("label", "create")),
        ),
        Operation(
            name="label.list",
            summary="List labels.",
            scope="read",
            mutating=False,
            params_model=ListLabelsParams,
            result_model=LabelListResult,
            handler=services.list_labels,
            route=HttpRoute("GET", "/labels"),
            cli=CliBinding(("label", "list")),
        ),
        Operation(
            name="initiative.create",
            summary="Create a cross-project initiative with a ranking weight.",
            scope="work.write",
            mutating=True,
            params_model=CreateInitiativeParams,
            result_model=InitiativeResult,
            handler=services.create_initiative,
            route=HttpRoute("POST", "/initiatives"),
            cli=CliBinding(("initiative", "create")),
        ),
        Operation(
            name="initiative.list",
            summary="List initiatives.",
            scope="read",
            mutating=False,
            params_model=ListInitiativesParams,
            result_model=InitiativeListResult,
            handler=services.list_initiatives,
            route=HttpRoute("GET", "/initiatives"),
            cli=CliBinding(("initiative", "list")),
        ),
        Operation(
            name="actor.create",
            summary="Register a human or agent so work can be assigned to it.",
            scope="admin",
            mutating=True,
            params_model=CreateActorParams,
            result_model=ActorResult,
            handler=services.create_actor,
            route=HttpRoute("POST", "/actors"),
            cli=CliBinding(("actor", "create")),
        ),
        Operation(
            name="actor.list",
            summary="List actors.",
            scope="read",
            mutating=False,
            params_model=ListActorsParams,
            result_model=ActorListResult,
            handler=services.list_actors,
            route=HttpRoute("GET", "/actors"),
            cli=CliBinding(("actor", "list")),
        ),
        Operation(
            name="workflow.list",
            summary="The state machine each work-item kind is governed by.",
            scope="read",
            mutating=False,
            params_model=WorkflowListParams,
            result_model=WorkflowListResult,
            handler=services.list_workflows,
            route=HttpRoute("GET", "/workflows"),
            cli=CliBinding(("workflow", "list")),
        ),
        # -- collection ----------------------------------------------------
        Operation(
            name="sweep",
            summary="Run collectors over the registered projects.",
            scope="project.write",
            mutating=True,
            params_model=SweepParams,
            result_model=SweepResult,
            handler=services.sweep,
            route=HttpRoute("POST", "/sweep"),
            cli=CliBinding(("sweep",)),
        ),
        Operation(
            name="coverage",
            summary="What has looked at what, and how long ago.",
            scope="read",
            mutating=False,
            params_model=CoverageParams,
            result_model=CoverageResult,
            handler=services.coverage,
            route=HttpRoute("GET", "/coverage"),
            cli=CliBinding(("coverage",)),
        ),
        Operation(
            name="observations.list",
            summary="Raw evidence, including subjects ranked views filter out.",
            scope="read",
            mutating=False,
            params_model=ObservationsParams,
            result_model=ObservationsResult,
            handler=services.observations,
            route=HttpRoute("GET", "/observations"),
            cli=CliBinding(("observations", "list")),
        ),
        Operation(
            name="deps",
            summary="Dependency references out of a project, and into it.",
            scope="read",
            mutating=False,
            params_model=DepsParams,
            result_model=DepsResult,
            handler=services.deps,
            route=HttpRoute("GET", "/deps"),
            cli=CliBinding(("deps",)),
        ),
        Operation(
            name="observations.prune",
            summary="Apply the retention policy to observation history.",
            scope="admin",
            mutating=True,
            params_model=PruneParams,
            result_model=PruneResult,
            handler=services.prune,
            route=HttpRoute("POST", "/observations/prune"),
            cli=CliBinding(("observations", "prune")),
        ),
        # -- observed-first ------------------------------------------------
        Operation(
            name="suppress",
            summary="Exclude an observed subject from ranked views.",
            scope="work.write",
            mutating=True,
            params_model=SuppressParams,
            result_model=SuppressionResult,
            handler=services.suppress,
            route=HttpRoute("POST", "/suppressions"),
            cli=CliBinding(("suppress",)),
        ),
        Operation(
            name="suppression.list",
            summary="List suppressions.",
            scope="read",
            mutating=False,
            params_model=ListSuppressionsParams,
            result_model=SuppressionListResult,
            handler=services.list_suppressions,
            route=HttpRoute("GET", "/suppressions"),
            cli=CliBinding(("suppression", "list")),
        ),
        Operation(
            name="suppression.revoke",
            summary="Revoke a suppression, returning the subject to ranked views.",
            scope="work.write",
            mutating=True,
            params_model=RevokeSuppressionParams,
            result_model=SuppressionResult,
            handler=services.revoke_suppression,
            route=HttpRoute("POST", "/suppressions/revoke"),
            cli=CliBinding(("suppression", "revoke")),
        ),
        Operation(
            name="work.adopt",
            summary="Promote an observed subject into a declared work item.",
            scope="work.write",
            mutating=True,
            params_model=AdoptParams,
            result_model=AdoptResult,
            handler=services.adopt,
            route=HttpRoute("POST", "/work/adopt"),
            cli=CliBinding(("work", "adopt")),
        ),
        # -- history -------------------------------------------------------
        Operation(
            name="events.list",
            summary="Read the cursor-based event feed.",
            scope="read",
            mutating=False,
            params_model=ListEventsParams,
            result_model=EventListResult,
            handler=services.list_events,
            route=HttpRoute("GET", "/events"),
            cli=CliBinding(("events", "list")),
        ),
        Operation(
            name="audit.list",
            summary="Query the audit log.",
            scope="read",
            mutating=False,
            params_model=ListAuditParams,
            result_model=AuditListResult,
            handler=services.list_audit,
            route=HttpRoute("GET", "/audit"),
            cli=CliBinding(("audit", "list")),
        ),
    ]
