"""The M1 operation set.

Every capability of the product, defined once. Adding an entry here is what
gives an operation a CLI command, a REST route with request and response
schemas, and an MCP tool — and the parity harness fails if any of the three
is missing (FR-A1, FR-A3).
"""

from __future__ import annotations

from typing import Any

from vogt.application import services
from vogt.application.models import (
    ActorListResult,
    ActorResult,
    AdoptParams,
    AdoptResult,
    AuditListResult,
    AuthDecisionListParams,
    AuthDecisionListResult,
    BacklogParams,
    BacklogResult,
    BackupParams,
    BackupResult,
    BoardListParams,
    BoardListResult,
    BugsParams,
    CommentParams,
    CommentResult,
    ComplianceParams,
    ComplianceResult,
    ConnectParams,
    ConnectResult,
    ContractCheckParams,
    ContractCheckResult,
    ContractEvaluateParams,
    CoverageParams,
    CoverageResult,
    CreateActorParams,
    CreateInitiativeParams,
    CreateLabelParams,
    CreateProjectParams,
    CreateProjectResult,
    CreateWorkParams,
    DepsParams,
    DepsResult,
    DriftDetectParams,
    DriftDetectResult,
    DriftListParams,
    DriftListResult,
    DriftResolveParams,
    DriftResult,
    EventListResult,
    ExportParams,
    ExportResult,
    GetProjectParams,
    GetWorkParams,
    ImportParams,
    ImportProjectParams,
    ImportProjectResult,
    ImportResult,
    InboxArchiveParams,
    InboxListParams,
    InboxListResult,
    InboxRestoreParams,
    InboxSnoozeParams,
    InboxTriageResult,
    InitiativeListResult,
    InitiativeResult,
    InitParams,
    InitResult,
    IssueTokenParams,
    IssueTokenResult,
    LabelListResult,
    LabelResult,
    ListActorsParams,
    ListAuditParams,
    ListEventsParams,
    ListInitiativesParams,
    ListLabelsParams,
    ListProjectsParams,
    ListSessionsParams,
    ListSuppressionsParams,
    ListTokensParams,
    ListWorkParams,
    McpStdioParams,
    McpStdioResult,
    MigrateParams,
    MigrateResult,
    NotificationsParams,
    NotificationsResult,
    ObservationsParams,
    ObservationsResult,
    OnboardParams,
    OnboardResult,
    ProjectBriefParams,
    ProjectBriefResult,
    ProjectListResult,
    ProjectResult,
    PruneParams,
    PruneResult,
    RegisterProjectParams,
    RelateWorkParams,
    RestoreParams,
    RestoreResult,
    RevokeSuppressionParams,
    RevokeTokenParams,
    ServeParams,
    ServeResult,
    SessionListResult,
    SessionResult,
    SetWriteBackParams,
    StartSessionParams,
    StatusParams,
    StatusResult,
    StopSessionParams,
    SuppressionListResult,
    SuppressionResult,
    SuppressParams,
    SweepParams,
    SweepResult,
    TokenListResult,
    TokenResult,
    TransitionProjectParams,
    TransitionWorkParams,
    UnrelateWorkParams,
    UpdateProjectParams,
    UpdateWorkParams,
    WhyParams,
    WhyResult,
    WorkflowListParams,
    WorkflowListResult,
    WorkListResult,
    WorkResult,
    WriteBackListParams,
    WriteBackListResult,
)
from vogt.registry.operation import CliBinding, HttpRoute, Operation


def build_operations() -> list[Operation[Any, Any]]:
    """Define every operation the M1 build exposes."""
    return [
        # -- instance ------------------------------------------------------
        Operation(
            name="init",
            summary="Create or bring forward the instance in the data directory.",
            scope="admin",
            mutating=False,
            params_model=InitParams,
            result_model=InitResult,
            handler=services.init_instance,
            route=HttpRoute("POST", "/instance/init"),
            cli=CliBinding(("init",)),
        ),
        Operation(
            name="migrate",
            summary="Bring both stores forward to this build's schema.",
            scope="admin",
            mutating=False,
            params_model=MigrateParams,
            result_model=MigrateResult,
            handler=services.migrate_instance,
            route=HttpRoute("POST", "/instance/migrate"),
            cli=CliBinding(("migrate",)),
        ),
        Operation(
            name="status",
            summary="Report instance identity, schema versions, and row counts.",
            scope="read",
            mutating=False,
            params_model=StatusParams,
            result_model=StatusResult,
            handler=services.status,
            route=HttpRoute("GET", "/status"),
            cli=CliBinding(("status",)),
        ),
        Operation(
            name="connect",
            summary="How to reach this instance, and the client configuration "
            "for doing so. Renders the connection document.",
            scope="read",
            mutating=False,
            params_model=ConnectParams,
            result_model=ConnectResult,
            handler=services.connect,
            route=HttpRoute("GET", "/connect"),
            cli=CliBinding(("connect",)),
        ),
        Operation(
            name="mcp.stdio",
            summary="Serve MCP over stdin/stdout until the stream closes.",
            scope="read",
            mutating=False,
            params_model=McpStdioParams,
            result_model=McpStdioResult,
            handler=services.serve_mcp_stdio,
            route=HttpRoute("POST", "/mcp/stdio"),
            cli=CliBinding(("mcp", "stdio")),
        ),
        # -- projects ------------------------------------------------------
        Operation(
            name="project.register",
            summary="Register an existing folder or repository as a project.",
            scope="project.write",
            mutating=True,
            params_model=RegisterProjectParams,
            result_model=ProjectResult,
            handler=services.register_project,
            route=HttpRoute("POST", "/projects"),
            cli=CliBinding(("project", "register")),
        ),
        Operation(
            name="project.create",
            summary="Scaffold a contract-compliant skeleton, then register it.",
            scope="project.write",
            mutating=True,
            params_model=CreateProjectParams,
            result_model=CreateProjectResult,
            handler=services.create_project,
            route=HttpRoute("POST", "/projects/create"),
            cli=CliBinding(("project", "create")),
        ),
        Operation(
            name="project.import",
            summary="Clone a GitHub repository into the import root, register "
            "it, and consolidate its existing forge state.",
            scope="project.write",
            mutating=True,
            params_model=ImportProjectParams,
            result_model=ImportProjectResult,
            handler=services.import_project,
            route=HttpRoute("POST", "/projects/import"),
            cli=CliBinding(("project", "import")),
        ),
        Operation(
            name="project.get",
            summary="Fetch one project by slug.",
            scope="read",
            mutating=False,
            params_model=GetProjectParams,
            result_model=ProjectResult,
            handler=services.get_project,
            route=HttpRoute("GET", "/projects/get"),
            cli=CliBinding(("project", "get")),
        ),
        Operation(
            name="project.list",
            summary="List registered projects.",
            scope="read",
            mutating=False,
            params_model=ListProjectsParams,
            result_model=ProjectListResult,
            handler=services.list_projects,
            route=HttpRoute("GET", "/projects"),
            cli=CliBinding(("project", "list")),
        ),
        Operation(
            name="project.brief",
            summary="The per-repo view: state, work, bugs, version, compliance.",
            scope="read",
            mutating=False,
            params_model=ProjectBriefParams,
            result_model=ProjectBriefResult,
            handler=services.brief_project,
            route=HttpRoute("GET", "/projects/brief"),
            cli=CliBinding(("project", "brief")),
        ),
        Operation(
            name="project.update",
            summary="Correct a project's declared repo URL or exclusions.",
            scope="project.write",
            mutating=True,
            params_model=UpdateProjectParams,
            result_model=ProjectResult,
            handler=services.update_project,
            route=HttpRoute("POST", "/projects/update"),
            cli=CliBinding(("project", "update")),
        ),
        Operation(
            name="project.transition",
            summary="Move a project through its lifecycle states.",
            scope="project.write",
            mutating=True,
            params_model=TransitionProjectParams,
            result_model=ProjectResult,
            handler=services.transition_project,
            route=HttpRoute("POST", "/projects/transition"),
            cli=CliBinding(("project", "transition")),
        ),
        # -- work ----------------------------------------------------------
        Operation(
            name="work.create",
            summary="Create a work item (feature / bug / chore / question).",
            scope="work.write",
            mutating=True,
            params_model=CreateWorkParams,
            result_model=WorkResult,
            handler=services.create_work,
            route=HttpRoute("POST", "/work"),
            cli=CliBinding(("work", "create")),
        ),
        Operation(
            name="work.get",
            summary="Fetch one work item with its relations, labels and comments.",
            scope="read",
            mutating=False,
            params_model=GetWorkParams,
            result_model=WorkResult,
            handler=services.get_work,
            route=HttpRoute("GET", "/work/get"),
            cli=CliBinding(("work", "get")),
        ),
        Operation(
            name="work.list",
            summary="List work items with filters.",
            scope="read",
            mutating=False,
            params_model=ListWorkParams,
            result_model=WorkListResult,
            handler=services.list_work,
            route=HttpRoute("GET", "/work"),
            cli=CliBinding(("work", "list")),
        ),
        Operation(
            name="board.list",
            summary="Read bounded, independently pageable Board cells in one snapshot.",
            scope="read",
            mutating=False,
            params_model=BoardListParams,
            result_model=BoardListResult,
            handler=services.list_board,
            # A structured cell batch belongs in a body even though the
            # operation is read-only; adapters still derive it from here.
            route=HttpRoute("POST", "/board/list"),
            cli=CliBinding(("board", "list")),
        ),
        Operation(
            name="work.update",
            summary="Change a work item's fields, assignee, or labels.",
            scope="work.write",
            mutating=True,
            params_model=UpdateWorkParams,
            result_model=WorkResult,
            handler=services.update_work,
            route=HttpRoute("POST", "/work/update"),
            cli=CliBinding(("work", "update")),
        ),
        Operation(
            name="work.transition",
            summary="Move a work item to another state, validating the edge.",
            scope="work.write",
            mutating=True,
            params_model=TransitionWorkParams,
            result_model=WorkResult,
            handler=services.transition_work,
            route=HttpRoute("POST", "/work/transition"),
            cli=CliBinding(("work", "transition")),
        ),
        Operation(
            name="work.relate",
            summary="Add a typed relation between two work items.",
            scope="work.write",
            mutating=True,
            params_model=RelateWorkParams,
            result_model=WorkResult,
            handler=services.relate_work,
            route=HttpRoute("POST", "/work/relate"),
            cli=CliBinding(("work", "relate")),
        ),
        Operation(
            name="work.unrelate",
            summary="Remove a typed relation between two work items.",
            scope="work.write",
            mutating=True,
            params_model=UnrelateWorkParams,
            result_model=WorkResult,
            handler=services.unrelate_work,
            route=HttpRoute("POST", "/work/unrelate"),
            cli=CliBinding(("work", "unrelate")),
        ),
        Operation(
            name="work.comment",
            summary="Comment on a work item, attributed to the acting actor.",
            scope="work.write",
            mutating=True,
            params_model=CommentParams,
            result_model=CommentResult,
            handler=services.comment_work,
            route=HttpRoute("POST", "/work/comment"),
            cli=CliBinding(("work", "comment")),
        ),
        # -- views ---------------------------------------------------------
        Operation(
            name="backlog",
            summary="The ranked backlog, globally or for one project.",
            scope="read",
            mutating=False,
            params_model=BacklogParams,
            result_model=BacklogResult,
            handler=services.backlog,
            route=HttpRoute("GET", "/backlog"),
            cli=CliBinding(("backlog",)),
        ),
        Operation(
            name="bugs",
            summary="Open bugs across every project, ranked.",
            scope="read",
            mutating=False,
            params_model=BugsParams,
            result_model=BacklogResult,
            handler=services.bugs,
            route=HttpRoute("GET", "/bugs"),
            cli=CliBinding(("bugs",)),
        ),
        Operation(
            name="why",
            summary="Per-input score contributions for one ranked item.",
            scope="read",
            mutating=False,
            params_model=WhyParams,
            result_model=WhyResult,
            handler=services.why,
            route=HttpRoute("GET", "/why"),
            cli=CliBinding(("why",)),
        ),
        # -- taxonomy ------------------------------------------------------
        Operation(
            name="label.create",
            summary="Define a label.",
            scope="work.write",
            mutating=True,
            params_model=CreateLabelParams,
            result_model=LabelResult,
            handler=services.create_label,
            route=HttpRoute("POST", "/labels"),
            cli=CliBinding(("label", "create")),
        ),
        Operation(
            name="label.list",
            summary="List labels.",
            scope="read",
            mutating=False,
            params_model=ListLabelsParams,
            result_model=LabelListResult,
            handler=services.list_labels,
            route=HttpRoute("GET", "/labels"),
            cli=CliBinding(("label", "list")),
        ),
        Operation(
            name="initiative.create",
            summary="Create a cross-project initiative with a ranking weight.",
            scope="work.write",
            mutating=True,
            params_model=CreateInitiativeParams,
            result_model=InitiativeResult,
            handler=services.create_initiative,
            route=HttpRoute("POST", "/initiatives"),
            cli=CliBinding(("initiative", "create")),
        ),
        Operation(
            name="initiative.list",
            summary="List initiatives.",
            scope="read",
            mutating=False,
            params_model=ListInitiativesParams,
            result_model=InitiativeListResult,
            handler=services.list_initiatives,
            route=HttpRoute("GET", "/initiatives"),
            cli=CliBinding(("initiative", "list")),
        ),
        Operation(
            name="actor.create",
            summary="Register a human or agent so work can be assigned to it.",
            scope="admin",
            mutating=True,
            params_model=CreateActorParams,
            result_model=ActorResult,
            handler=services.create_actor,
            route=HttpRoute("POST", "/actors"),
            cli=CliBinding(("actor", "create")),
        ),
        Operation(
            name="actor.list",
            summary="List actors.",
            scope="read",
            mutating=False,
            params_model=ListActorsParams,
            result_model=ActorListResult,
            handler=services.list_actors,
            route=HttpRoute("GET", "/actors"),
            cli=CliBinding(("actor", "list")),
        ),
        Operation(
            name="workflow.list",
            summary="The state machine each work-item kind is governed by.",
            scope="read",
            mutating=False,
            params_model=WorkflowListParams,
            result_model=WorkflowListResult,
            handler=services.list_workflows,
            route=HttpRoute("GET", "/workflows"),
            cli=CliBinding(("workflow", "list")),
        ),
        # -- collection ----------------------------------------------------
        Operation(
            name="sweep",
            summary="Run collectors over the registered projects.",
            scope="project.write",
            mutating=True,
            params_model=SweepParams,
            result_model=SweepResult,
            handler=services.sweep,
            route=HttpRoute("POST", "/sweep"),
            cli=CliBinding(("sweep",)),
        ),
        Operation(
            name="coverage",
            summary="What has looked at what, and how long ago.",
            scope="read",
            mutating=False,
            params_model=CoverageParams,
            result_model=CoverageResult,
            handler=services.coverage,
            route=HttpRoute("GET", "/coverage"),
            cli=CliBinding(("coverage",)),
        ),
        Operation(
            name="observations.list",
            summary="Raw evidence, including subjects ranked views filter out.",
            scope="read",
            mutating=False,
            params_model=ObservationsParams,
            result_model=ObservationsResult,
            handler=services.observations,
            route=HttpRoute("GET", "/observations"),
            cli=CliBinding(("observations", "list")),
        ),
        Operation(
            name="deps",
            summary="Dependency references out of a project, and into it.",
            scope="read",
            mutating=False,
            params_model=DepsParams,
            result_model=DepsResult,
            handler=services.deps,
            route=HttpRoute("GET", "/deps"),
            cli=CliBinding(("deps",)),
        ),
        Operation(
            name="observations.prune",
            summary="Apply the retention policy to observation history.",
            scope="admin",
            mutating=True,
            params_model=PruneParams,
            result_model=PruneResult,
            handler=services.prune,
            route=HttpRoute("POST", "/observations/prune"),
            cli=CliBinding(("observations", "prune")),
        ),
        # -- observed-first ------------------------------------------------
        Operation(
            name="suppress",
            summary="Exclude an observed subject from ranked views.",
            scope="work.write",
            mutating=True,
            params_model=SuppressParams,
            result_model=SuppressionResult,
            handler=services.suppress,
            route=HttpRoute("POST", "/suppressions"),
            cli=CliBinding(("suppress",)),
        ),
        Operation(
            name="suppression.list",
            summary="List suppressions.",
            scope="read",
            mutating=False,
            params_model=ListSuppressionsParams,
            result_model=SuppressionListResult,
            handler=services.list_suppressions,
            route=HttpRoute("GET", "/suppressions"),
            cli=CliBinding(("suppression", "list")),
        ),
        Operation(
            name="suppression.revoke",
            summary="Revoke a suppression, returning the subject to ranked views.",
            scope="work.write",
            mutating=True,
            params_model=RevokeSuppressionParams,
            result_model=SuppressionResult,
            handler=services.revoke_suppression,
            route=HttpRoute("POST", "/suppressions/revoke"),
            cli=CliBinding(("suppression", "revoke")),
        ),
        Operation(
            name="work.adopt",
            summary="Promote an observed subject into a declared work item.",
            scope="work.write",
            mutating=True,
            params_model=AdoptParams,
            result_model=AdoptResult,
            handler=services.adopt,
            route=HttpRoute("POST", "/work/adopt"),
            cli=CliBinding(("work", "adopt")),
        ),
        # -- contract and drift --------------------------------------------
        Operation(
            name="contract.evaluate",
            summary="Evaluate the contract against any path; stores nothing.",
            scope="read",
            mutating=False,
            params_model=ContractEvaluateParams,
            result_model=ContractCheckResult,
            handler=services.contract_evaluate,
            route=HttpRoute("POST", "/contract/evaluate"),
            cli=CliBinding(("contract", "evaluate")),
        ),
        Operation(
            name="contract.check",
            summary="Evaluate the project contract; returns every failing rule.",
            scope="project.write",
            mutating=True,
            params_model=ContractCheckParams,
            result_model=ContractCheckResult,
            handler=services.contract_check,
            route=HttpRoute("POST", "/contract/check"),
            cli=CliBinding(("contract", "check")),
        ),
        Operation(
            name="compliance",
            summary="A project's last recorded contract result, with its age.",
            scope="read",
            mutating=False,
            params_model=ComplianceParams,
            result_model=ComplianceResult,
            handler=services.compliance,
            route=HttpRoute("GET", "/compliance"),
            cli=CliBinding(("compliance",)),
        ),
        Operation(
            name="drift.detect",
            summary="Compare declared state against observation; raise proposals.",
            scope="project.write",
            mutating=True,
            params_model=DriftDetectParams,
            result_model=DriftDetectResult,
            handler=services.detect_drift,
            route=HttpRoute("POST", "/drift/detect"),
            cli=CliBinding(("drift", "detect")),
        ),
        Operation(
            name="drift.list",
            summary="Open drift proposals and their evidence.",
            scope="read",
            mutating=False,
            params_model=DriftListParams,
            result_model=DriftListResult,
            handler=services.list_drift,
            route=HttpRoute("GET", "/drift"),
            cli=CliBinding(("drift", "list")),
        ),
        Operation(
            name="drift.resolve",
            summary="Accept, reject, or contest a drift proposal.",
            scope="project.write",
            mutating=True,
            params_model=DriftResolveParams,
            result_model=DriftResult,
            handler=services.resolve_drift,
            route=HttpRoute("POST", "/drift/resolve"),
            cli=CliBinding(("drift", "resolve")),
        ),
        # -- service and identity ------------------------------------------
        Operation(
            name="serve",
            summary="Serve the API, MCP and health endpoints on one port.",
            scope="admin",
            mutating=False,
            params_model=ServeParams,
            result_model=ServeResult,
            handler=services.serve,
            route=HttpRoute("POST", "/instance/serve"),
            cli=CliBinding(("serve",)),
        ),
        # -- coding sessions (FR-E8) --------------------------------------
        #
        # Three operations, so the capability arrives on CLI, REST and MCP at
        # once (FR-A1). `session.start` is scoped `work.write` rather than
        # `admin`: opening a terminal on a bug is the ordinary act of working
        # on it, and gating it behind admin would mean the agents that most
        # need it are the ones that cannot.
        Operation(
            name="session.start",
            summary="Open a coding session for a work item or a project.",
            scope="work.write",
            mutating=True,
            params_model=StartSessionParams,
            result_model=SessionResult,
            handler=services.start_session,
            route=HttpRoute("POST", "/sessions"),
            cli=CliBinding(("session", "start")),
        ),
        Operation(
            name="session.list",
            summary="List coding sessions with their live activity state.",
            scope="read",
            mutating=False,
            params_model=ListSessionsParams,
            result_model=SessionListResult,
            handler=services.list_sessions,
            route=HttpRoute("GET", "/sessions"),
            cli=CliBinding(("session", "list")),
        ),
        Operation(
            name="session.stop",
            summary="Stop a coding session and revoke the token it ran with.",
            scope="work.write",
            mutating=True,
            params_model=StopSessionParams,
            result_model=SessionResult,
            handler=services.stop_session,
            route=HttpRoute("POST", "/sessions/stop"),
            cli=CliBinding(("session", "stop")),
        ),
        Operation(
            name="token.issue",
            summary="Issue a scoped token bound to an actor. Shown once.",
            scope="admin",
            mutating=True,
            params_model=IssueTokenParams,
            result_model=IssueTokenResult,
            handler=services.issue_token,
            route=HttpRoute("POST", "/tokens"),
            cli=CliBinding(("token", "issue")),
        ),
        Operation(
            name="token.list",
            summary="List tokens. Never returns a secret.",
            scope="admin",
            mutating=False,
            params_model=ListTokensParams,
            result_model=TokenListResult,
            handler=services.list_tokens,
            route=HttpRoute("GET", "/tokens"),
            cli=CliBinding(("token", "list")),
        ),
        Operation(
            name="token.revoke",
            summary="Revoke a token.",
            scope="admin",
            mutating=True,
            params_model=RevokeTokenParams,
            result_model=TokenResult,
            handler=services.revoke_token,
            route=HttpRoute("POST", "/tokens/revoke"),
            cli=CliBinding(("token", "revoke")),
        ),
        Operation(
            name="auth.decisions",
            summary="The allow and deny log. The denials are the interesting half.",
            scope="admin",
            mutating=False,
            params_model=AuthDecisionListParams,
            result_model=AuthDecisionListResult,
            handler=services.list_auth_decisions,
            route=HttpRoute("GET", "/auth/decisions"),
            cli=CliBinding(("auth", "decisions")),
        ),
        # -- backup and portability ----------------------------------------
        Operation(
            name="backup",
            summary="Snapshot both stores with a schema-version manifest.",
            scope="admin",
            mutating=False,
            params_model=BackupParams,
            result_model=BackupResult,
            handler=services.backup,
            route=HttpRoute("POST", "/instance/backup"),
            cli=CliBinding(("backup",)),
        ),
        Operation(
            name="restore",
            summary="Verify a backup's manifest, then replace the live stores.",
            scope="admin",
            mutating=False,
            params_model=RestoreParams,
            result_model=RestoreResult,
            handler=services.restore,
            route=HttpRoute("POST", "/instance/restore"),
            cli=CliBinding(("restore",)),
        ),
        Operation(
            name="export",
            summary="Write the declared entities as JSON.",
            scope="read",
            mutating=False,
            params_model=ExportParams,
            result_model=ExportResult,
            handler=services.export_instance,
            route=HttpRoute("POST", "/instance/export"),
            cli=CliBinding(("export",)),
        ),
        Operation(
            name="import",
            summary="Report what an export contains. Read-only in v1.",
            scope="admin",
            mutating=False,
            params_model=ImportParams,
            result_model=ImportResult,
            handler=services.import_instance,
            route=HttpRoute("POST", "/instance/import"),
            cli=CliBinding(("import",)),
        ),
        # -- the forge module (M5) -----------------------------------------
        Operation(
            name="forge.onboard",
            summary="Read a repository's existing issues, PRs, labels and "
            "releases into observations. Changes nothing upstream.",
            scope="project.write",
            mutating=True,
            params_model=OnboardParams,
            result_model=OnboardResult,
            handler=services.onboard,
            route=HttpRoute("POST", "/forge/onboard"),
            cli=CliBinding(("forge", "onboard")),
        ),
        Operation(
            name="forge.writeback",
            summary="Set a project's write-back policy: none, comment_only, full.",
            # FR-S11: the scope named `writeback` gates arming write-back, and
            # nothing else does. It required `project.write` until r13, which
            # left `writeback` gating no operation at all — a scope a token can
            # hold and be granted nothing by. Arming upstream pushes is a
            # different power from registering a project or moving its
            # lifecycle state, and a deployment that wants an agent to manage
            # projects without ever letting it speak to a forge now has a way
            # to say so.
            scope="writeback",
            mutating=True,
            params_model=SetWriteBackParams,
            result_model=ProjectResult,
            handler=services.set_write_back,
            route=HttpRoute("POST", "/forge/writeback"),
            cli=CliBinding(("forge", "writeback")),
        ),
        Operation(
            name="forge.actions",
            summary="The ledger of what Vogt has said upstream, and what landed.",
            scope="read",
            mutating=False,
            params_model=WriteBackListParams,
            result_model=WriteBackListResult,
            handler=services.list_write_backs,
            route=HttpRoute("GET", "/forge/actions"),
            cli=CliBinding(("forge", "actions")),
        ),
        # -- history -------------------------------------------------------
        Operation(
            name="events.list",
            summary="Read the cursor-based event feed.",
            scope="read",
            mutating=False,
            params_model=ListEventsParams,
            result_model=EventListResult,
            handler=services.list_events,
            route=HttpRoute("GET", "/events"),
            cli=CliBinding(("events", "list")),
        ),
        Operation(
            name="notifications",
            summary="What GitHub is trying to say about the registered "
            "projects. Separate from the events feed, which is this "
            "instance's own history.",
            scope="read",
            mutating=False,
            params_model=NotificationsParams,
            result_model=NotificationsResult,
            handler=services.list_notifications,
            route=HttpRoute("GET", "/notifications"),
            cli=CliBinding(("notifications",)),
        ),
        Operation(
            name="inbox.list",
            summary="List the normalized attention Inbox with coverage.",
            scope="read",
            mutating=False,
            params_model=InboxListParams,
            result_model=InboxListResult,
            handler=services.list_inbox,
            route=HttpRoute("GET", "/inbox"),
            cli=CliBinding(("inbox", "list")),
        ),
        Operation(
            name="inbox.archive",
            summary="Archive one normalized Inbox occurrence.",
            scope="work.write",
            mutating=True,
            params_model=InboxArchiveParams,
            result_model=InboxTriageResult,
            handler=services.archive_inbox,
            route=HttpRoute("POST", "/inbox/archive"),
            cli=CliBinding(("inbox", "archive")),
        ),
        Operation(
            name="inbox.snooze",
            summary="Snooze one normalized Inbox occurrence until a deadline.",
            scope="work.write",
            mutating=True,
            params_model=InboxSnoozeParams,
            result_model=InboxTriageResult,
            handler=services.snooze_inbox,
            route=HttpRoute("POST", "/inbox/snooze"),
            cli=CliBinding(("inbox", "snooze")),
        ),
        Operation(
            name="inbox.restore",
            summary="Restore one archived or snoozed Inbox occurrence.",
            scope="work.write",
            mutating=True,
            params_model=InboxRestoreParams,
            result_model=InboxTriageResult,
            handler=services.restore_inbox,
            route=HttpRoute("POST", "/inbox/restore"),
            cli=CliBinding(("inbox", "restore")),
        ),
        Operation(
            name="audit.list",
            summary="Query the audit log.",
            scope="read",
            mutating=False,
            params_model=ListAuditParams,
            result_model=AuditListResult,
            handler=services.list_audit,
            route=HttpRoute("GET", "/audit"),
            cli=CliBinding(("audit", "list")),
        ),
    ]
