/** Deterministic browser-scale fixtures for the #422 release check. */

import type { DemoState } from "./fixtures";

export const STRESS_PROFILE = {
  workItems: 2_000,
  files: 5_000,
  fileDepth: 8,
  sessions: 32,
} as const;

export function requestedDemoScale(raw: string | null): number {
  const value = Number(raw);
  return Number.isSafeInteger(value) && value > 0 ? value : 0;
}

/** Expand the normal demo state using the same wire shapes as production. */
export function scaleDemoState(base: DemoState, requested: number): DemoState {
  if (requested <= 0) return base;
  const item: DemoState["work"][number] | undefined = base.work[0];
  if (!item) return base;

  const work = [...base.work];
  const states = ["open", "in_progress", "review", "done"] as const;
  for (let index = work.length; index < requested; index += 1) {
    const ordinal = index + 1;
    const generated = {
      ...item,
      id: `work-scale-${ordinal}`,
      ref: `WI-${ordinal}`,
      title: `Scale fixture work item ${ordinal}`,
      body: "Generated by the #422 browser stress profile.",
      state: states[index % states.length]!,
      priority: index % 5 === 0 ? "p0" : "p2",
      project_slug: index % 2 === 0 ? "orbit" : "lighthouse",
      initiative_id: index % 3 === 0 ? "init-demo" : "init-reliability",
      labels: ["scale"],
      relations: [],
      updated_at: "2026-08-24T14:00:00Z",
      effort: index % 2 === 0 ? "medium" : null,
    } as DemoState["work"][number];
    work.push(generated);
  }

  const sessions = { ...base.sessions };
  for (let index = Object.keys(sessions).length; index < STRESS_PROFILE.sessions; index += 1) {
    const id = `scale-session-${index + 1}`;
    sessions[id] = {
      id,
      name: `Scale session ${index + 1}`,
      activity: index % 7 === 0 ? "waiting-for-input" : index % 3 === 0 ? "running" : "idle",
      exit_code: null,
      cwd: index % 2 === 0 ? "/Working/orbit" : "/Working/lighthouse",
      scrollback_bytes: 131072,
      created_at: "2026-08-24T12:00:00Z",
      activity_changed_at: "2026-08-24T14:00:00Z",
    };
  }

  const files = { ...base.files };
  const branch = Array.from({ length: STRESS_PROFILE.fileDepth }, (_unused, depth) =>
    `depth-${String(depth + 1).padStart(2, "0")}`,
  );
  for (let index = 0; index < STRESS_PROFILE.files; index += 1) {
    const prefix = branch.slice(0, (index % STRESS_PROFILE.fileDepth) + 1).join("/");
    const directory = prefix ? `stress/${prefix}` : "stress";
    const path = `${directory}/file-${String(index + 1).padStart(4, "0")}.ts`;
    files[path] = {
      content: `export const stressFixture = ${index};\n`,
      mtime: 1787581200000 + index,
      hash: `scale-${index.toString(16)}`,
    };
  }

  return { ...base, work, sessions, files };
}
